apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
  annotations:
    kubernetes.io/ingress.class: mynginx
spec:
  rules:
    - http:
      paths:
        - path: /
          backend:
            serviceName: stable-service
            servicePort: 80   
        - path: /dev
          backend:
            serviceName: canary-service
            servicePort: 8080              